IF OBJECT_ID('Channel', 'U') IS NOT NULL
	DROP TABLE Channel;

CREATE TABLE Channel (
	Id NVARCHAR (50) NOT NULL,
	Url NVARCHAR (250) NULL,
	Title NVARCHAR (250) NOT NULL,
	Thumbnail NVARCHAR (2000) NOT NULL,
	StaleAfter DATETIMEOFFSET NOT NULL,
	VisibleAfter DATETIMEOFFSET NOT NULL,

	CONSTRAINT PK_Channel PRIMARY KEY (Id),
	CONSTRAINT UK_Channel_Url UNIQUE (Url)
);
