SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'youtubed.UK_Channel_Url', N'UQ') IS NOT NULL
BEGIN
    ALTER TABLE youtubed.Channel
        DROP CONSTRAINT UK_Channel_Url;
END;

COMMIT TRANSACTION;
