DROP TYPE IF EXISTS [ChannelVideoType];
DROP TABLE IF EXISTS [ShareLink];
DROP TABLE IF EXISTS [ListChannel];
DROP TABLE IF EXISTS [ChannelVideo];
DROP TABLE IF EXISTS [List];
DROP TABLE IF EXISTS [Channel];

CREATE TABLE Channel (
	Id NVARCHAR (50) NOT NULL,
	Url NVARCHAR (250) NULL,
	Title NVARCHAR (250) NOT NULL,
	Thumbnail NVARCHAR (2000) NOT NULL,
	PlaylistId NVARCHAR (50) NOT NULL,
	StaleAfter DATETIMEOFFSET NOT NULL,
	VisibleAfter DATETIMEOFFSET NOT NULL,

	CONSTRAINT PK_Channel PRIMARY KEY (Id),
	CONSTRAINT UK_Channel_Url UNIQUE (Url)
);

CREATE TABLE List (
	Id UNIQUEIDENTIFIER NOT NULL,
	Token BINARY (40) NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	ExpiredAfter DATETIMEOFFSET NOT NULL,

	CONSTRAINT FK_List PRIMARY KEY (Id)
);

CREATE TABLE ShareLink (
	Password NVARCHAR (100) NOT NULL,
	ListId UNIQUEIDENTIFIER NOT NULL,
	CreatedAt DATETIMEOFFSET NOT NULL,
	ExpiresAfter DATETIMEOFFSET NOT NULL,
	UsedAt DATETIMEOFFSET NULL,

	CONSTRAINT PK_ShareLink PRIMARY KEY (Password),
	CONSTRAINT FK_ShareLink_List FOREIGN KEY (ListId) REFERENCES List (Id) ON DELETE CASCADE
);

CREATE INDEX IX_ShareLink_ListId_CreatedAt ON ShareLink (ListId, CreatedAt DESC);

CREATE TABLE ChannelVideo (
	ChannelId NVARCHAR (50) NOT NULL,
	Id NVARCHAR (50) NOT NULL,
	Title NVARCHAR (100) NOT NULL,
	Duration BIGINT NOT NULL,
	PublishedAt DATETIMEOFFSET NOT NULL,
	Thumbnail NVARCHAR(2000) NULL,

	CONSTRAINT PK_ChannelVideo PRIMARY KEY (ChannelId, Id),
	CONSTRAINT FK_ChannelVideo_Channel FOREIGN KEY (ChannelId) REFERENCES Channel (Id) ON DELETE CASCADE
);

CREATE TABLE ListChannel (
	ListId UNIQUEIDENTIFIER NOT NULL,
	ChannelId NVARCHAR (50) NOT NULL,

	CONSTRAINT PK_ListChannel PRIMARY KEY (ListId, ChannelId),
	CONSTRAINT FK_ListChannel_List FOREIGN KEY (ListId) REFERENCES List (Id) ON DELETE CASCADE,
	CONSTRAINT FK_ListChannel_Channel FOREIGN KEY (ChannelId) REFERENCES Channel (Id)
);

CREATE TYPE ChannelVideoType AS TABLE (
	ChannelId NVARCHAR (50) NOT NULL,
	Id NVARCHAR (50) NOT NULL,
	Title NVARCHAR (100) NOT NULL,
	Duration BIGINT NOT NULL,
	PublishedAt DATETIMEOFFSET NOT NULL,
	Thumbnail NVARCHAR(2000) NULL
);
