<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>6a3676e8-3e2c-4433-976f-4e27f06e1306</UserSecretsId>
    <AssemblyVersion>2.0.0.1</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.70.0.3847" />
    <PackageReference Include="Humanizer.Core" Version="2.13.14" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Shared\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

</Project>
